const AuthActionTypes = {
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    USER_LOADED: 'USER_LOADED',
    AUTH_ERROR: 'AUTH_ERROR ',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',
    ACCOUNT_DELETED: 'ACCOUNT_DELETED'
}

export default AuthActionTypes; 